/*
 * generated by Xtext 2.24.0
 */
package fr.diverse.moda.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.diverse.moda.ide.contentassist.antlr.internal.InternalModaParser;
import fr.diverse.moda.services.ModaGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ModaParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ModaGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ModaGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getMODAModelAccess().getAlternatives_4_1_1(), "rule__MODAModel__Alternatives_4_1_1");
			builder.put(grammarAccess.getMODAElementAccess().getAlternatives(), "rule__MODAElement__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getModelKindAccess().getAlternatives(), "rule__ModelKind__Alternatives");
			builder.put(grammarAccess.getDataKindAccess().getAlternatives(), "rule__DataKind__Alternatives");
			builder.put(grammarAccess.getRelationKindAccess().getAlternatives(), "rule__RelationKind__Alternatives");
			builder.put(grammarAccess.getMODAModelAccess().getGroup(), "rule__MODAModel__Group__0");
			builder.put(grammarAccess.getMODAModelAccess().getGroup_4(), "rule__MODAModel__Group_4__0");
			builder.put(grammarAccess.getMODAModelAccess().getGroup_4_1(), "rule__MODAModel__Group_4_1__0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getDataAccess().getGroup(), "rule__Data__Group__0");
			builder.put(grammarAccess.getRunningSoftwareAccess().getGroup(), "rule__RunningSoftware__Group__0");
			builder.put(grammarAccess.getSTSAccess().getGroup(), "rule__STS__Group__0");
			builder.put(grammarAccess.getMODARelationAccess().getGroup(), "rule__MODARelation__Group__0");
			builder.put(grammarAccess.getMODAModelAccess().getNameAssignment_2(), "rule__MODAModel__NameAssignment_2");
			builder.put(grammarAccess.getMODAModelAccess().getModelAssignment_4_0(), "rule__MODAModel__ModelAssignment_4_0");
			builder.put(grammarAccess.getMODAModelAccess().getModelAssignment_4_1_1_0(), "rule__MODAModel__ModelAssignment_4_1_1_0");
			builder.put(grammarAccess.getMODAModelAccess().getDataAssignment_4_1_1_1(), "rule__MODAModel__DataAssignment_4_1_1_1");
			builder.put(grammarAccess.getMODAModelAccess().getSoftwareAssignment_4_1_1_2(), "rule__MODAModel__SoftwareAssignment_4_1_1_2");
			builder.put(grammarAccess.getMODAModelAccess().getStsAssignment_4_1_1_3(), "rule__MODAModel__StsAssignment_4_1_1_3");
			builder.put(grammarAccess.getMODAModelAccess().getModarelationAssignment_4_1_1_4(), "rule__MODAModel__ModarelationAssignment_4_1_1_4");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_2(), "rule__Model__NameAssignment_2");
			builder.put(grammarAccess.getModelAccess().getKindAssignment_3(), "rule__Model__KindAssignment_3");
			builder.put(grammarAccess.getModelAccess().getDescriptionAssignment_4(), "rule__Model__DescriptionAssignment_4");
			builder.put(grammarAccess.getDataAccess().getNameAssignment_2(), "rule__Data__NameAssignment_2");
			builder.put(grammarAccess.getDataAccess().getKindAssignment_3(), "rule__Data__KindAssignment_3");
			builder.put(grammarAccess.getDataAccess().getDescriptionAssignment_4(), "rule__Data__DescriptionAssignment_4");
			builder.put(grammarAccess.getRunningSoftwareAccess().getNameAssignment_2(), "rule__RunningSoftware__NameAssignment_2");
			builder.put(grammarAccess.getSTSAccess().getNameAssignment_2(), "rule__STS__NameAssignment_2");
			builder.put(grammarAccess.getMODARelationAccess().getNameAssignment_2(), "rule__MODARelation__NameAssignment_2");
			builder.put(grammarAccess.getMODARelationAccess().getKindAssignment_3(), "rule__MODARelation__KindAssignment_3");
			builder.put(grammarAccess.getMODARelationAccess().getSrcAssignment_4(), "rule__MODARelation__SrcAssignment_4");
			builder.put(grammarAccess.getMODARelationAccess().getTgtAssignment_6(), "rule__MODARelation__TgtAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ModaGrammarAccess grammarAccess;

	@Override
	protected InternalModaParser createParser() {
		InternalModaParser result = new InternalModaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ModaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
