/*
 * generated by Xtext 2.24.0
 */
package fr.diverse.moda;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ModaStandaloneSetup extends ModaStandaloneSetupGenerated {

	public static void doSetup() {
		new ModaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
