/*
 * generated by Xtext 2.24.0
 */
package fr.diverse.moda.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/diverse/moda/parser/antlr/internal/InternalModa.tokens");
	}
}
