/*
 * generated by Xtext 2.24.0
 */
package fr.diverse.moda.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModaScopeProvider extends DelegatingScopeProvider {
}
