/*
 * generated by Xtext 2.24.0
 */
package fr.diverse.moda.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ModaGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class MODAModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.MODAModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMODAModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMODAModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cModelKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cModelAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cModelModelParserRuleCall_4_2_0 = (RuleCall)cModelAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cModelAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cModelModelParserRuleCall_4_3_1_0 = (RuleCall)cModelAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDataAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cDataDataParserRuleCall_5_2_0 = (RuleCall)cDataAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDataAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_5_3_1_0 = (RuleCall)cDataAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSoftwareKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSoftwareAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSoftwareRunningSoftwareParserRuleCall_6_1_0 = (RuleCall)cSoftwareAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cStsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cStsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cStsSTSParserRuleCall_7_1_0 = (RuleCall)cStsAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cRelationKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cModarelationAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cModarelationMODARelationParserRuleCall_8_2_0 = (RuleCall)cModarelationAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cModarelationAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cModarelationMODARelationParserRuleCall_8_3_1_0 = (RuleCall)cModarelationAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//MODAModel:
		//	{MODAModel}
		//	'MODAModel'
		//	name=EString
		//	'{' ('model' '{' model+=Model ("," model+=Model)* '}')? ('data' '{' data+=Data ("," data+=Data)* '}')? ('software'
		//	software=RunningSoftware)? ('sts' sts=STS)? ('relation' '{' modarelation+=MODARelation ("," modarelation+=MODARelation
		//	)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MODAModel}
		//'MODAModel'
		//name=EString
		//'{' ('model' '{' model+=Model ("," model+=Model)* '}')? ('data' '{' data+=Data ("," data+=Data)* '}')? ('software'
		//software=RunningSoftware)? ('sts' sts=STS)? ('relation' '{' modarelation+=MODARelation ("," modarelation+=MODARelation)*
		//'}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{MODAModel}
		public Action getMODAModelAction_0() { return cMODAModelAction_0; }
		
		//'MODAModel'
		public Keyword getMODAModelKeyword_1() { return cMODAModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('model' '{' model+=Model ("," model+=Model)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'model'
		public Keyword getModelKeyword_4_0() { return cModelKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//model+=Model
		public Assignment getModelAssignment_4_2() { return cModelAssignment_4_2; }
		
		//Model
		public RuleCall getModelModelParserRuleCall_4_2_0() { return cModelModelParserRuleCall_4_2_0; }
		
		//("," model+=Model)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//model+=Model
		public Assignment getModelAssignment_4_3_1() { return cModelAssignment_4_3_1; }
		
		//Model
		public RuleCall getModelModelParserRuleCall_4_3_1_0() { return cModelModelParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('data' '{' data+=Data ("," data+=Data)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'data'
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//data+=Data
		public Assignment getDataAssignment_5_2() { return cDataAssignment_5_2; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_5_2_0() { return cDataDataParserRuleCall_5_2_0; }
		
		//("," data+=Data)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//data+=Data
		public Assignment getDataAssignment_5_3_1() { return cDataAssignment_5_3_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_5_3_1_0() { return cDataDataParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('software' software=RunningSoftware)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'software'
		public Keyword getSoftwareKeyword_6_0() { return cSoftwareKeyword_6_0; }
		
		//software=RunningSoftware
		public Assignment getSoftwareAssignment_6_1() { return cSoftwareAssignment_6_1; }
		
		//RunningSoftware
		public RuleCall getSoftwareRunningSoftwareParserRuleCall_6_1_0() { return cSoftwareRunningSoftwareParserRuleCall_6_1_0; }
		
		//('sts' sts=STS)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'sts'
		public Keyword getStsKeyword_7_0() { return cStsKeyword_7_0; }
		
		//sts=STS
		public Assignment getStsAssignment_7_1() { return cStsAssignment_7_1; }
		
		//STS
		public RuleCall getStsSTSParserRuleCall_7_1_0() { return cStsSTSParserRuleCall_7_1_0; }
		
		//('relation' '{' modarelation+=MODARelation ("," modarelation+=MODARelation)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'relation'
		public Keyword getRelationKeyword_8_0() { return cRelationKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//modarelation+=MODARelation
		public Assignment getModarelationAssignment_8_2() { return cModarelationAssignment_8_2; }
		
		//MODARelation
		public RuleCall getModarelationMODARelationParserRuleCall_8_2_0() { return cModarelationMODARelationParserRuleCall_8_2_0; }
		
		//("," modarelation+=MODARelation)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//modarelation+=MODARelation
		public Assignment getModarelationAssignment_8_3_1() { return cModarelationAssignment_8_3_1; }
		
		//MODARelation
		public RuleCall getModarelationMODARelationParserRuleCall_8_3_1_0() { return cModarelationMODARelationParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class MODAElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.MODAElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cModelParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDataParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRunningSoftwareParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSTSParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//MODAElement:
		//	Model | Data | RunningSoftware | STS;
		@Override public ParserRule getRule() { return rule; }
		
		//Model | Data | RunningSoftware | STS
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Model
		public RuleCall getModelParserRuleCall_0() { return cModelParserRuleCall_0; }
		
		//Data
		public RuleCall getDataParserRuleCall_1() { return cDataParserRuleCall_1; }
		
		//RunningSoftware
		public RuleCall getRunningSoftwareParserRuleCall_2() { return cRunningSoftwareParserRuleCall_2; }
		
		//STS
		public RuleCall getSTSParserRuleCall_3() { return cSTSParserRuleCall_3; }
	}
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cKindAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cKindModelKindEnumRuleCall_2_0 = (RuleCall)cKindAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cQuotationMarkKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//Model:
		//	{Model} name=EString kind=ModelKind ('"' description=EString '"')?// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
		//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Model} name=EString kind=ModelKind ('"' description=EString '"')?
		public Group getGroup() { return cGroup; }
		
		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//kind=ModelKind
		public Assignment getKindAssignment_2() { return cKindAssignment_2; }
		
		//ModelKind
		public RuleCall getKindModelKindEnumRuleCall_2_0() { return cKindModelKindEnumRuleCall_2_0; }
		
		//('"' description=EString '"')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_3_0() { return cQuotationMarkKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_3_2() { return cQuotationMarkKeyword_3_2; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.Data");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDataAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cKindAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cKindDataKindEnumRuleCall_2_0 = (RuleCall)cKindAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cQuotationMarkKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//Data:
		//	{Data} name=EString kind=DataKind ('"' description=EString '"')?// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
		//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Data} name=EString kind=DataKind ('"' description=EString '"')?
		public Group getGroup() { return cGroup; }
		
		//{Data}
		public Action getDataAction_0() { return cDataAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//kind=DataKind
		public Assignment getKindAssignment_2() { return cKindAssignment_2; }
		
		//DataKind
		public RuleCall getKindDataKindEnumRuleCall_2_0() { return cKindDataKindEnumRuleCall_2_0; }
		
		//('"' description=EString '"')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_3_0() { return cQuotationMarkKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_3_2() { return cQuotationMarkKeyword_3_2; }
	}
	public class RunningSoftwareElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.RunningSoftware");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRunningSoftwareAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//RunningSoftware:
		//	{RunningSoftware} name=EString// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
		//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{RunningSoftware} name=EString
		public Group getGroup() { return cGroup; }
		
		//{RunningSoftware}
		public Action getRunningSoftwareAction_0() { return cRunningSoftwareAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class STSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.STS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSTSAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//STS:
		//	{STS} name=EString// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
		//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{STS} name=EString
		public Group getGroup() { return cGroup; }
		
		//{STS}
		public Action getSTSAction_0() { return cSTSAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class MODARelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.MODARelation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMODARelationAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cKindAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cKindRelationKindEnumRuleCall_2_0 = (RuleCall)cKindAssignment_2.eContents().get(0);
		private final Assignment cSrcAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSrcMODAElementCrossReference_3_0 = (CrossReference)cSrcAssignment_3.eContents().get(0);
		private final RuleCall cSrcMODAElementEStringParserRuleCall_3_0_1 = (RuleCall)cSrcMODAElementCrossReference_3_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTgtKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTgtAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTgtMODAElementCrossReference_5_1_0 = (CrossReference)cTgtAssignment_5_1.eContents().get(0);
		private final RuleCall cTgtMODAElementEStringParserRuleCall_5_1_0_1 = (RuleCall)cTgtMODAElementCrossReference_5_1_0.eContents().get(1);
		
		//MODARelation:
		//	{MODARelation} name=EString kind=RelationKind src=[MODAElement|EString] '->' ('tgt' tgt=[MODAElement|EString]);
		@Override public ParserRule getRule() { return rule; }
		
		//{MODARelation} name=EString kind=RelationKind src=[MODAElement|EString] '->' ('tgt' tgt=[MODAElement|EString])
		public Group getGroup() { return cGroup; }
		
		//{MODARelation}
		public Action getMODARelationAction_0() { return cMODARelationAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//kind=RelationKind
		public Assignment getKindAssignment_2() { return cKindAssignment_2; }
		
		//RelationKind
		public RuleCall getKindRelationKindEnumRuleCall_2_0() { return cKindRelationKindEnumRuleCall_2_0; }
		
		//src=[MODAElement|EString]
		public Assignment getSrcAssignment_3() { return cSrcAssignment_3; }
		
		//[MODAElement|EString]
		public CrossReference getSrcMODAElementCrossReference_3_0() { return cSrcMODAElementCrossReference_3_0; }
		
		//EString
		public RuleCall getSrcMODAElementEStringParserRuleCall_3_0_1() { return cSrcMODAElementEStringParserRuleCall_3_0_1; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_4() { return cHyphenMinusGreaterThanSignKeyword_4; }
		
		//('tgt' tgt=[MODAElement|EString])
		public Group getGroup_5() { return cGroup_5; }
		
		//'tgt'
		public Keyword getTgtKeyword_5_0() { return cTgtKeyword_5_0; }
		
		//tgt=[MODAElement|EString]
		public Assignment getTgtAssignment_5_1() { return cTgtAssignment_5_1; }
		
		//[MODAElement|EString]
		public CrossReference getTgtMODAElementCrossReference_5_1_0() { return cTgtMODAElementCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTgtMODAElementEStringParserRuleCall_5_1_0_1() { return cTgtMODAElementEStringParserRuleCall_5_1_0_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	public class ModelKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.ModelKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPrescriptiveEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPrescriptivePrescriptiveKeyword_0_0 = (Keyword)cPrescriptiveEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPredictiveEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPredictivePredictiveKeyword_1_0 = (Keyword)cPredictiveEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDescriptiveEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDescriptiveDescriptiveKeyword_2_0 = (Keyword)cDescriptiveEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ModelKind:
		//	prescriptive | predictive | descriptive;
		public EnumRule getRule() { return rule; }
		
		//prescriptive | predictive | descriptive
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//prescriptive
		public EnumLiteralDeclaration getPrescriptiveEnumLiteralDeclaration_0() { return cPrescriptiveEnumLiteralDeclaration_0; }
		
		//'prescriptive'
		public Keyword getPrescriptivePrescriptiveKeyword_0_0() { return cPrescriptivePrescriptiveKeyword_0_0; }
		
		//predictive
		public EnumLiteralDeclaration getPredictiveEnumLiteralDeclaration_1() { return cPredictiveEnumLiteralDeclaration_1; }
		
		//'predictive'
		public Keyword getPredictivePredictiveKeyword_1_0() { return cPredictivePredictiveKeyword_1_0; }
		
		//descriptive
		public EnumLiteralDeclaration getDescriptiveEnumLiteralDeclaration_2() { return cDescriptiveEnumLiteralDeclaration_2; }
		
		//'descriptive'
		public Keyword getDescriptiveDescriptiveKeyword_2_0() { return cDescriptiveDescriptiveKeyword_2_0; }
	}
	public class DataKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.DataKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cInputEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cInputInputKeyword_0_0 = (Keyword)cInputEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOutputEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOutputOutputKeyword_1_0 = (Keyword)cOutputEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cExternalEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cExternalExternalKeyword_2_0 = (Keyword)cExternalEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMeasuredEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMeasuredMeasuredKeyword_3_0 = (Keyword)cMeasuredEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum DataKind:
		//	input | output | external | measured;
		public EnumRule getRule() { return rule; }
		
		//input | output | external | measured
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//input
		public EnumLiteralDeclaration getInputEnumLiteralDeclaration_0() { return cInputEnumLiteralDeclaration_0; }
		
		//'input'
		public Keyword getInputInputKeyword_0_0() { return cInputInputKeyword_0_0; }
		
		//output
		public EnumLiteralDeclaration getOutputEnumLiteralDeclaration_1() { return cOutputEnumLiteralDeclaration_1; }
		
		//'output'
		public Keyword getOutputOutputKeyword_1_0() { return cOutputOutputKeyword_1_0; }
		
		//external
		public EnumLiteralDeclaration getExternalEnumLiteralDeclaration_2() { return cExternalEnumLiteralDeclaration_2; }
		
		//'external'
		public Keyword getExternalExternalKeyword_2_0() { return cExternalExternalKeyword_2_0; }
		
		//measured
		public EnumLiteralDeclaration getMeasuredEnumLiteralDeclaration_3() { return cMeasuredEnumLiteralDeclaration_3; }
		
		//'measured'
		public Keyword getMeasuredMeasuredKeyword_3_0() { return cMeasuredMeasuredKeyword_3_0; }
	}
	public class RelationKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.RelationKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGenerationEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGenerationGenerationKeyword_0_0 = (Keyword)cGenerationEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cEnactmentEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cEnactmentEnactmentKeyword_1_0 = (Keyword)cEnactmentEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDeploymentEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDeploymentDeploymentKeyword_2_0 = (Keyword)cDeploymentEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cInputEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cInputInputKeyword_3_0 = (Keyword)cInputEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cOutputEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cOutputOutputKeyword_4_0 = (Keyword)cOutputEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cMeasurementEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cMeasurementMeasurementKeyword_5_0 = (Keyword)cMeasurementEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cOtherInterplayEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cOtherInterplayOtherInterplayKeyword_6_0 = (Keyword)cOtherInterplayEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cGeneralizationEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cGeneralizationGeneralizationKeyword_7_0 = (Keyword)cGeneralizationEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cPreparationEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cPreparationPreparationKeyword_8_0 = (Keyword)cPreparationEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cAnalysisEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cAnalysisAnalysisKeyword_9_0 = (Keyword)cAnalysisEnumLiteralDeclaration_9.eContents().get(0);
		
		//enum RelationKind:
		//	generation | enactment | deployment | input | output | measurement | otherInterplay | generalization | preparation |
		//	analysis;
		public EnumRule getRule() { return rule; }
		
		//generation | enactment | deployment | input | output | measurement | otherInterplay | generalization |
		//preparation | analysis
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//generation
		public EnumLiteralDeclaration getGenerationEnumLiteralDeclaration_0() { return cGenerationEnumLiteralDeclaration_0; }
		
		//'generation'
		public Keyword getGenerationGenerationKeyword_0_0() { return cGenerationGenerationKeyword_0_0; }
		
		//enactment
		public EnumLiteralDeclaration getEnactmentEnumLiteralDeclaration_1() { return cEnactmentEnumLiteralDeclaration_1; }
		
		//'enactment'
		public Keyword getEnactmentEnactmentKeyword_1_0() { return cEnactmentEnactmentKeyword_1_0; }
		
		//deployment
		public EnumLiteralDeclaration getDeploymentEnumLiteralDeclaration_2() { return cDeploymentEnumLiteralDeclaration_2; }
		
		//'deployment'
		public Keyword getDeploymentDeploymentKeyword_2_0() { return cDeploymentDeploymentKeyword_2_0; }
		
		//input
		public EnumLiteralDeclaration getInputEnumLiteralDeclaration_3() { return cInputEnumLiteralDeclaration_3; }
		
		//'input'
		public Keyword getInputInputKeyword_3_0() { return cInputInputKeyword_3_0; }
		
		//output
		public EnumLiteralDeclaration getOutputEnumLiteralDeclaration_4() { return cOutputEnumLiteralDeclaration_4; }
		
		//'output'
		public Keyword getOutputOutputKeyword_4_0() { return cOutputOutputKeyword_4_0; }
		
		//measurement
		public EnumLiteralDeclaration getMeasurementEnumLiteralDeclaration_5() { return cMeasurementEnumLiteralDeclaration_5; }
		
		//'measurement'
		public Keyword getMeasurementMeasurementKeyword_5_0() { return cMeasurementMeasurementKeyword_5_0; }
		
		//otherInterplay
		public EnumLiteralDeclaration getOtherInterplayEnumLiteralDeclaration_6() { return cOtherInterplayEnumLiteralDeclaration_6; }
		
		//'otherInterplay'
		public Keyword getOtherInterplayOtherInterplayKeyword_6_0() { return cOtherInterplayOtherInterplayKeyword_6_0; }
		
		//generalization
		public EnumLiteralDeclaration getGeneralizationEnumLiteralDeclaration_7() { return cGeneralizationEnumLiteralDeclaration_7; }
		
		//'generalization'
		public Keyword getGeneralizationGeneralizationKeyword_7_0() { return cGeneralizationGeneralizationKeyword_7_0; }
		
		//preparation
		public EnumLiteralDeclaration getPreparationEnumLiteralDeclaration_8() { return cPreparationEnumLiteralDeclaration_8; }
		
		//'preparation'
		public Keyword getPreparationPreparationKeyword_8_0() { return cPreparationPreparationKeyword_8_0; }
		
		//analysis
		public EnumLiteralDeclaration getAnalysisEnumLiteralDeclaration_9() { return cAnalysisEnumLiteralDeclaration_9; }
		
		//'analysis'
		public Keyword getAnalysisAnalysisKeyword_9_0() { return cAnalysisAnalysisKeyword_9_0; }
	}
	
	private final MODAModelElements pMODAModel;
	private final MODAElementElements pMODAElement;
	private final ModelElements pModel;
	private final DataElements pData;
	private final RunningSoftwareElements pRunningSoftware;
	private final STSElements pSTS;
	private final MODARelationElements pMODARelation;
	private final EStringElements pEString;
	private final ModelKindElements eModelKind;
	private final DataKindElements eDataKind;
	private final RelationKindElements eRelationKind;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ModaGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMODAModel = new MODAModelElements();
		this.pMODAElement = new MODAElementElements();
		this.pModel = new ModelElements();
		this.pData = new DataElements();
		this.pRunningSoftware = new RunningSoftwareElements();
		this.pSTS = new STSElements();
		this.pMODARelation = new MODARelationElements();
		this.pEString = new EStringElements();
		this.eModelKind = new ModelKindElements();
		this.eDataKind = new DataKindElements();
		this.eRelationKind = new RelationKindElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.diverse.moda.Moda".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MODAModel:
	//	{MODAModel}
	//	'MODAModel'
	//	name=EString
	//	'{' ('model' '{' model+=Model ("," model+=Model)* '}')? ('data' '{' data+=Data ("," data+=Data)* '}')? ('software'
	//	software=RunningSoftware)? ('sts' sts=STS)? ('relation' '{' modarelation+=MODARelation ("," modarelation+=MODARelation
	//	)* '}')?
	//	'}';
	public MODAModelElements getMODAModelAccess() {
		return pMODAModel;
	}
	
	public ParserRule getMODAModelRule() {
		return getMODAModelAccess().getRule();
	}
	
	//MODAElement:
	//	Model | Data | RunningSoftware | STS;
	public MODAElementElements getMODAElementAccess() {
		return pMODAElement;
	}
	
	public ParserRule getMODAElementRule() {
		return getMODAElementAccess().getRule();
	}
	
	//Model:
	//	{Model} name=EString kind=ModelKind ('"' description=EString '"')?// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
	//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Data:
	//	{Data} name=EString kind=DataKind ('"' description=EString '"')?// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
	//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
	//;
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//RunningSoftware:
	//	{RunningSoftware} name=EString// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
	//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
	//;
	public RunningSoftwareElements getRunningSoftwareAccess() {
		return pRunningSoftware;
	}
	
	public ParserRule getRunningSoftwareRule() {
		return getRunningSoftwareAccess().getRule();
	}
	
	//STS:
	//	{STS} name=EString// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
	//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
	//;
	public STSElements getSTSAccess() {
		return pSTS;
	}
	
	public ParserRule getSTSRule() {
		return getSTSAccess().getRule();
	}
	
	//MODARelation:
	//	{MODARelation} name=EString kind=RelationKind src=[MODAElement|EString] '->' ('tgt' tgt=[MODAElement|EString]);
	public MODARelationElements getMODARelationAccess() {
		return pMODARelation;
	}
	
	public ParserRule getMODARelationRule() {
		return getMODARelationAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum ModelKind:
	//	prescriptive | predictive | descriptive;
	public ModelKindElements getModelKindAccess() {
		return eModelKind;
	}
	
	public EnumRule getModelKindRule() {
		return getModelKindAccess().getRule();
	}
	
	//enum DataKind:
	//	input | output | external | measured;
	public DataKindElements getDataKindAccess() {
		return eDataKind;
	}
	
	public EnumRule getDataKindRule() {
		return getDataKindAccess().getRule();
	}
	
	//enum RelationKind:
	//	generation | enactment | deployment | input | output | measurement | otherInterplay | generalization | preparation |
	//	analysis;
	public RelationKindElements getRelationKindAccess() {
		return eRelationKind;
	}
	
	public EnumRule getRelationKindRule() {
		return getRelationKindAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
