/*
 * generated by Xtext 2.24.0
 */
package fr.diverse.moda.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ModaGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class MODAModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.MODAModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMODAModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMODAModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cModelAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cModelModelParserRuleCall_4_0_0 = (RuleCall)cModelAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Alternatives cAlternatives_4_1_1 = (Alternatives)cGroup_4_1.eContents().get(1);
		private final Assignment cModelAssignment_4_1_1_0 = (Assignment)cAlternatives_4_1_1.eContents().get(0);
		private final RuleCall cModelModelParserRuleCall_4_1_1_0_0 = (RuleCall)cModelAssignment_4_1_1_0.eContents().get(0);
		private final Assignment cDataAssignment_4_1_1_1 = (Assignment)cAlternatives_4_1_1.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_4_1_1_1_0 = (RuleCall)cDataAssignment_4_1_1_1.eContents().get(0);
		private final Assignment cSoftwareAssignment_4_1_1_2 = (Assignment)cAlternatives_4_1_1.eContents().get(2);
		private final RuleCall cSoftwareRunningSoftwareParserRuleCall_4_1_1_2_0 = (RuleCall)cSoftwareAssignment_4_1_1_2.eContents().get(0);
		private final Assignment cStsAssignment_4_1_1_3 = (Assignment)cAlternatives_4_1_1.eContents().get(3);
		private final RuleCall cStsSTSParserRuleCall_4_1_1_3_0 = (RuleCall)cStsAssignment_4_1_1_3.eContents().get(0);
		private final Assignment cModarelationAssignment_4_1_1_4 = (Assignment)cAlternatives_4_1_1.eContents().get(4);
		private final RuleCall cModarelationMODARelationParserRuleCall_4_1_1_4_0 = (RuleCall)cModarelationAssignment_4_1_1_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//MODAModel:
		//	{MODAModel}
		//	'MODAModel'
		//	name=EString
		//	'{' (model+=Model ("," (model+=Model | data+=Data | software=RunningSoftware | sts=STS | modarelation+=MODARelation))*
		//	)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MODAModel}
		//'MODAModel'
		//name=EString
		//'{' (model+=Model ("," (model+=Model | data+=Data | software=RunningSoftware | sts=STS | modarelation+=MODARelation))*)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{MODAModel}
		public Action getMODAModelAction_0() { return cMODAModelAction_0; }
		
		//'MODAModel'
		public Keyword getMODAModelKeyword_1() { return cMODAModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(model+=Model ("," (model+=Model | data+=Data | software=RunningSoftware | sts=STS | modarelation+=MODARelation))*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//model+=Model
		public Assignment getModelAssignment_4_0() { return cModelAssignment_4_0; }
		
		//Model
		public RuleCall getModelModelParserRuleCall_4_0_0() { return cModelModelParserRuleCall_4_0_0; }
		
		//("," (model+=Model | data+=Data | software=RunningSoftware | sts=STS | modarelation+=MODARelation))*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//(model+=Model | data+=Data | software=RunningSoftware | sts=STS | modarelation+=MODARelation)
		public Alternatives getAlternatives_4_1_1() { return cAlternatives_4_1_1; }
		
		//model+=Model
		public Assignment getModelAssignment_4_1_1_0() { return cModelAssignment_4_1_1_0; }
		
		//Model
		public RuleCall getModelModelParserRuleCall_4_1_1_0_0() { return cModelModelParserRuleCall_4_1_1_0_0; }
		
		//data+=Data
		public Assignment getDataAssignment_4_1_1_1() { return cDataAssignment_4_1_1_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_1_1_1_0() { return cDataDataParserRuleCall_4_1_1_1_0; }
		
		//software=RunningSoftware
		public Assignment getSoftwareAssignment_4_1_1_2() { return cSoftwareAssignment_4_1_1_2; }
		
		//RunningSoftware
		public RuleCall getSoftwareRunningSoftwareParserRuleCall_4_1_1_2_0() { return cSoftwareRunningSoftwareParserRuleCall_4_1_1_2_0; }
		
		//sts=STS
		public Assignment getStsAssignment_4_1_1_3() { return cStsAssignment_4_1_1_3; }
		
		//STS
		public RuleCall getStsSTSParserRuleCall_4_1_1_3_0() { return cStsSTSParserRuleCall_4_1_1_3_0; }
		
		//modarelation+=MODARelation
		public Assignment getModarelationAssignment_4_1_1_4() { return cModarelationAssignment_4_1_1_4; }
		
		//MODARelation
		public RuleCall getModarelationMODARelationParserRuleCall_4_1_1_4_0() { return cModarelationMODARelationParserRuleCall_4_1_1_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class MODAElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.MODAElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cModelParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDataParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRunningSoftwareParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSTSParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//MODAElement:
		//	Model | Data | RunningSoftware | STS;
		@Override public ParserRule getRule() { return rule; }
		
		//Model | Data | RunningSoftware | STS
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Model
		public RuleCall getModelParserRuleCall_0() { return cModelParserRuleCall_0; }
		
		//Data
		public RuleCall getDataParserRuleCall_1() { return cDataParserRuleCall_1; }
		
		//RunningSoftware
		public RuleCall getRunningSoftwareParserRuleCall_2() { return cRunningSoftwareParserRuleCall_2; }
		
		//STS
		public RuleCall getSTSParserRuleCall_3() { return cSTSParserRuleCall_3; }
	}
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cKindAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cKindModelKindEnumRuleCall_3_0 = (RuleCall)cKindAssignment_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionEStringParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		
		//Model:
		//	{Model}
		//	'model'
		//	name=EString kind=ModelKind description=EString?// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
		//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Model}
		//'model'
		//name=EString kind=ModelKind description=EString?
		public Group getGroup() { return cGroup; }
		
		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }
		
		//'model'
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//kind=ModelKind
		public Assignment getKindAssignment_3() { return cKindAssignment_3; }
		
		//ModelKind
		public RuleCall getKindModelKindEnumRuleCall_3_0() { return cKindModelKindEnumRuleCall_3_0; }
		
		//description=EString?
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_0() { return cDescriptionEStringParserRuleCall_4_0; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.Data");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDataAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDataKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cKindAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cKindDataKindEnumRuleCall_3_0 = (RuleCall)cKindAssignment_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionEStringParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		
		//Data:
		//	{Data}
		//	'data'
		//	name=EString kind=DataKind description=EString?// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
		//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Data}
		//'data'
		//name=EString kind=DataKind description=EString?
		public Group getGroup() { return cGroup; }
		
		//{Data}
		public Action getDataAction_0() { return cDataAction_0; }
		
		//'data'
		public Keyword getDataKeyword_1() { return cDataKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//kind=DataKind
		public Assignment getKindAssignment_3() { return cKindAssignment_3; }
		
		//DataKind
		public RuleCall getKindDataKindEnumRuleCall_3_0() { return cKindDataKindEnumRuleCall_3_0; }
		
		//description=EString?
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_0() { return cDescriptionEStringParserRuleCall_4_0; }
	}
	public class RunningSoftwareElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.RunningSoftware");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRunningSoftwareAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSoftwareKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RunningSoftware:
		//	{RunningSoftware}
		//	'software'
		//	name=EString// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
		//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{RunningSoftware}
		//'software'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{RunningSoftware}
		public Action getRunningSoftwareAction_0() { return cRunningSoftwareAction_0; }
		
		//'software'
		public Keyword getSoftwareKeyword_1() { return cSoftwareKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class STSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.STS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSTSAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//STS:
		//	{STS}
		//	'sts'
		//	name=EString// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
		//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{STS}
		//'sts'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{STS}
		public Action getSTSAction_0() { return cSTSAction_0; }
		
		//'sts'
		public Keyword getStsKeyword_1() { return cStsKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class MODARelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.MODARelation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMODARelationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRelationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cKindAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cKindRelationKindEnumRuleCall_3_0 = (RuleCall)cKindAssignment_3.eContents().get(0);
		private final Assignment cSrcAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cSrcMODAElementCrossReference_4_0 = (CrossReference)cSrcAssignment_4.eContents().get(0);
		private final RuleCall cSrcMODAElementEStringParserRuleCall_4_0_1 = (RuleCall)cSrcMODAElementCrossReference_4_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTgtAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cTgtMODAElementCrossReference_6_0 = (CrossReference)cTgtAssignment_6.eContents().get(0);
		private final RuleCall cTgtMODAElementEStringParserRuleCall_6_0_1 = (RuleCall)cTgtMODAElementCrossReference_6_0.eContents().get(1);
		
		//MODARelation:
		//	{MODARelation}
		//	'relation'
		//	name=EString kind=RelationKind src=[MODAElement|EString] '->' tgt=[MODAElement|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//{MODARelation}
		//'relation'
		//name=EString kind=RelationKind src=[MODAElement|EString] '->' tgt=[MODAElement|EString]
		public Group getGroup() { return cGroup; }
		
		//{MODARelation}
		public Action getMODARelationAction_0() { return cMODARelationAction_0; }
		
		//'relation'
		public Keyword getRelationKeyword_1() { return cRelationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//kind=RelationKind
		public Assignment getKindAssignment_3() { return cKindAssignment_3; }
		
		//RelationKind
		public RuleCall getKindRelationKindEnumRuleCall_3_0() { return cKindRelationKindEnumRuleCall_3_0; }
		
		//src=[MODAElement|EString]
		public Assignment getSrcAssignment_4() { return cSrcAssignment_4; }
		
		//[MODAElement|EString]
		public CrossReference getSrcMODAElementCrossReference_4_0() { return cSrcMODAElementCrossReference_4_0; }
		
		//EString
		public RuleCall getSrcMODAElementEStringParserRuleCall_4_0_1() { return cSrcMODAElementEStringParserRuleCall_4_0_1; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_5() { return cHyphenMinusGreaterThanSignKeyword_5; }
		
		//tgt=[MODAElement|EString]
		public Assignment getTgtAssignment_6() { return cTgtAssignment_6; }
		
		//[MODAElement|EString]
		public CrossReference getTgtMODAElementCrossReference_6_0() { return cTgtMODAElementCrossReference_6_0; }
		
		//EString
		public RuleCall getTgtMODAElementEStringParserRuleCall_6_0_1() { return cTgtMODAElementEStringParserRuleCall_6_0_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	public class ModelKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.ModelKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPrescriptiveEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPrescriptivePrescriptiveKeyword_0_0 = (Keyword)cPrescriptiveEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPredictiveEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPredictivePredictiveKeyword_1_0 = (Keyword)cPredictiveEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDescriptiveEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDescriptiveDescriptiveKeyword_2_0 = (Keyword)cDescriptiveEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ModelKind:
		//	prescriptive | predictive | descriptive;
		public EnumRule getRule() { return rule; }
		
		//prescriptive | predictive | descriptive
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//prescriptive
		public EnumLiteralDeclaration getPrescriptiveEnumLiteralDeclaration_0() { return cPrescriptiveEnumLiteralDeclaration_0; }
		
		//'prescriptive'
		public Keyword getPrescriptivePrescriptiveKeyword_0_0() { return cPrescriptivePrescriptiveKeyword_0_0; }
		
		//predictive
		public EnumLiteralDeclaration getPredictiveEnumLiteralDeclaration_1() { return cPredictiveEnumLiteralDeclaration_1; }
		
		//'predictive'
		public Keyword getPredictivePredictiveKeyword_1_0() { return cPredictivePredictiveKeyword_1_0; }
		
		//descriptive
		public EnumLiteralDeclaration getDescriptiveEnumLiteralDeclaration_2() { return cDescriptiveEnumLiteralDeclaration_2; }
		
		//'descriptive'
		public Keyword getDescriptiveDescriptiveKeyword_2_0() { return cDescriptiveDescriptiveKeyword_2_0; }
	}
	public class DataKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.DataKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cInputEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cInputInputKeyword_0_0 = (Keyword)cInputEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOutputEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOutputOutputKeyword_1_0 = (Keyword)cOutputEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cExternalEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cExternalExternalKeyword_2_0 = (Keyword)cExternalEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMeasuredEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMeasuredMeasuredKeyword_3_0 = (Keyword)cMeasuredEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum DataKind:
		//	input | output | external | measured;
		public EnumRule getRule() { return rule; }
		
		//input | output | external | measured
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//input
		public EnumLiteralDeclaration getInputEnumLiteralDeclaration_0() { return cInputEnumLiteralDeclaration_0; }
		
		//'input'
		public Keyword getInputInputKeyword_0_0() { return cInputInputKeyword_0_0; }
		
		//output
		public EnumLiteralDeclaration getOutputEnumLiteralDeclaration_1() { return cOutputEnumLiteralDeclaration_1; }
		
		//'output'
		public Keyword getOutputOutputKeyword_1_0() { return cOutputOutputKeyword_1_0; }
		
		//external
		public EnumLiteralDeclaration getExternalEnumLiteralDeclaration_2() { return cExternalEnumLiteralDeclaration_2; }
		
		//'external'
		public Keyword getExternalExternalKeyword_2_0() { return cExternalExternalKeyword_2_0; }
		
		//measured
		public EnumLiteralDeclaration getMeasuredEnumLiteralDeclaration_3() { return cMeasuredEnumLiteralDeclaration_3; }
		
		//'measured'
		public Keyword getMeasuredMeasuredKeyword_3_0() { return cMeasuredMeasuredKeyword_3_0; }
	}
	public class RelationKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.diverse.moda.Moda.RelationKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGenerationEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGenerationGenerationKeyword_0_0 = (Keyword)cGenerationEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cEnactmentEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cEnactmentEnactmentKeyword_1_0 = (Keyword)cEnactmentEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDeploymentEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDeploymentDeploymentKeyword_2_0 = (Keyword)cDeploymentEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cInputEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cInputInputKeyword_3_0 = (Keyword)cInputEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cOutputEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cOutputOutputKeyword_4_0 = (Keyword)cOutputEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cMeasurementEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cMeasurementMeasurementKeyword_5_0 = (Keyword)cMeasurementEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cOtherInterplayEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cOtherInterplayOtherInterplayKeyword_6_0 = (Keyword)cOtherInterplayEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cGeneralizationEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cGeneralizationGeneralizationKeyword_7_0 = (Keyword)cGeneralizationEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cPreparationEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cPreparationPreparationKeyword_8_0 = (Keyword)cPreparationEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cAnalysisEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cAnalysisAnalysisKeyword_9_0 = (Keyword)cAnalysisEnumLiteralDeclaration_9.eContents().get(0);
		
		//enum RelationKind:
		//	generation | enactment | deployment | input | output | measurement | otherInterplay | generalization | preparation |
		//	analysis;
		public EnumRule getRule() { return rule; }
		
		//generation | enactment | deployment | input | output | measurement | otherInterplay | generalization |
		//preparation | analysis
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//generation
		public EnumLiteralDeclaration getGenerationEnumLiteralDeclaration_0() { return cGenerationEnumLiteralDeclaration_0; }
		
		//'generation'
		public Keyword getGenerationGenerationKeyword_0_0() { return cGenerationGenerationKeyword_0_0; }
		
		//enactment
		public EnumLiteralDeclaration getEnactmentEnumLiteralDeclaration_1() { return cEnactmentEnumLiteralDeclaration_1; }
		
		//'enactment'
		public Keyword getEnactmentEnactmentKeyword_1_0() { return cEnactmentEnactmentKeyword_1_0; }
		
		//deployment
		public EnumLiteralDeclaration getDeploymentEnumLiteralDeclaration_2() { return cDeploymentEnumLiteralDeclaration_2; }
		
		//'deployment'
		public Keyword getDeploymentDeploymentKeyword_2_0() { return cDeploymentDeploymentKeyword_2_0; }
		
		//input
		public EnumLiteralDeclaration getInputEnumLiteralDeclaration_3() { return cInputEnumLiteralDeclaration_3; }
		
		//'input'
		public Keyword getInputInputKeyword_3_0() { return cInputInputKeyword_3_0; }
		
		//output
		public EnumLiteralDeclaration getOutputEnumLiteralDeclaration_4() { return cOutputEnumLiteralDeclaration_4; }
		
		//'output'
		public Keyword getOutputOutputKeyword_4_0() { return cOutputOutputKeyword_4_0; }
		
		//measurement
		public EnumLiteralDeclaration getMeasurementEnumLiteralDeclaration_5() { return cMeasurementEnumLiteralDeclaration_5; }
		
		//'measurement'
		public Keyword getMeasurementMeasurementKeyword_5_0() { return cMeasurementMeasurementKeyword_5_0; }
		
		//otherInterplay
		public EnumLiteralDeclaration getOtherInterplayEnumLiteralDeclaration_6() { return cOtherInterplayEnumLiteralDeclaration_6; }
		
		//'otherInterplay'
		public Keyword getOtherInterplayOtherInterplayKeyword_6_0() { return cOtherInterplayOtherInterplayKeyword_6_0; }
		
		//generalization
		public EnumLiteralDeclaration getGeneralizationEnumLiteralDeclaration_7() { return cGeneralizationEnumLiteralDeclaration_7; }
		
		//'generalization'
		public Keyword getGeneralizationGeneralizationKeyword_7_0() { return cGeneralizationGeneralizationKeyword_7_0; }
		
		//preparation
		public EnumLiteralDeclaration getPreparationEnumLiteralDeclaration_8() { return cPreparationEnumLiteralDeclaration_8; }
		
		//'preparation'
		public Keyword getPreparationPreparationKeyword_8_0() { return cPreparationPreparationKeyword_8_0; }
		
		//analysis
		public EnumLiteralDeclaration getAnalysisEnumLiteralDeclaration_9() { return cAnalysisEnumLiteralDeclaration_9; }
		
		//'analysis'
		public Keyword getAnalysisAnalysisKeyword_9_0() { return cAnalysisAnalysisKeyword_9_0; }
	}
	
	private final MODAModelElements pMODAModel;
	private final MODAElementElements pMODAElement;
	private final ModelElements pModel;
	private final DataElements pData;
	private final RunningSoftwareElements pRunningSoftware;
	private final STSElements pSTS;
	private final MODARelationElements pMODARelation;
	private final EStringElements pEString;
	private final ModelKindElements eModelKind;
	private final DataKindElements eDataKind;
	private final RelationKindElements eRelationKind;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ModaGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMODAModel = new MODAModelElements();
		this.pMODAElement = new MODAElementElements();
		this.pModel = new ModelElements();
		this.pData = new DataElements();
		this.pRunningSoftware = new RunningSoftwareElements();
		this.pSTS = new STSElements();
		this.pMODARelation = new MODARelationElements();
		this.pEString = new EStringElements();
		this.eModelKind = new ModelKindElements();
		this.eDataKind = new DataKindElements();
		this.eRelationKind = new RelationKindElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.diverse.moda.Moda".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MODAModel:
	//	{MODAModel}
	//	'MODAModel'
	//	name=EString
	//	'{' (model+=Model ("," (model+=Model | data+=Data | software=RunningSoftware | sts=STS | modarelation+=MODARelation))*
	//	)?
	//	'}';
	public MODAModelElements getMODAModelAccess() {
		return pMODAModel;
	}
	
	public ParserRule getMODAModelRule() {
		return getMODAModelAccess().getRule();
	}
	
	//MODAElement:
	//	Model | Data | RunningSoftware | STS;
	public MODAElementElements getMODAElementAccess() {
		return pMODAElement;
	}
	
	public ParserRule getMODAElementRule() {
		return getMODAElementAccess().getRule();
	}
	
	//Model:
	//	{Model}
	//	'model'
	//	name=EString kind=ModelKind description=EString?// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
	//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Data:
	//	{Data}
	//	'data'
	//	name=EString kind=DataKind description=EString?// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
	//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
	//;
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//RunningSoftware:
	//	{RunningSoftware}
	//	'software'
	//	name=EString// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
	//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
	//;
	public RunningSoftwareElements getRunningSoftwareAccess() {
		return pRunningSoftware;
	}
	
	public ParserRule getRunningSoftwareRule() {
		return getRunningSoftwareAccess().getRule();
	}
	
	//STS:
	//	{STS}
	//	'sts'
	//	name=EString// ('outgoing' '(' outgoing+=[MODARelation|EString] ( "," outgoing+=[MODARelation|EString])* ')' )?
	//// ('incoming' '(' incoming+=[MODARelation|EString] ( "," incoming+=[MODARelation|EString])* ')' )?
	//;
	public STSElements getSTSAccess() {
		return pSTS;
	}
	
	public ParserRule getSTSRule() {
		return getSTSAccess().getRule();
	}
	
	//MODARelation:
	//	{MODARelation}
	//	'relation'
	//	name=EString kind=RelationKind src=[MODAElement|EString] '->' tgt=[MODAElement|EString];
	public MODARelationElements getMODARelationAccess() {
		return pMODARelation;
	}
	
	public ParserRule getMODARelationRule() {
		return getMODARelationAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum ModelKind:
	//	prescriptive | predictive | descriptive;
	public ModelKindElements getModelKindAccess() {
		return eModelKind;
	}
	
	public EnumRule getModelKindRule() {
		return getModelKindAccess().getRule();
	}
	
	//enum DataKind:
	//	input | output | external | measured;
	public DataKindElements getDataKindAccess() {
		return eDataKind;
	}
	
	public EnumRule getDataKindRule() {
		return getDataKindAccess().getRule();
	}
	
	//enum RelationKind:
	//	generation | enactment | deployment | input | output | measurement | otherInterplay | generalization | preparation |
	//	analysis;
	public RelationKindElements getRelationKindAccess() {
		return eRelationKind;
	}
	
	public EnumRule getRelationKindRule() {
		return getRelationKindAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
