/*
 * generated by Xtext 2.24.0
 */
package fr.diverse.moda.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ModaUiModule extends AbstractModaUiModule {

	public ModaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
